[package]
name = "blockchain-in-rust"
version = "0.1.0"
authors = ["Zabirov M <devozm.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
